-- CREATE TABLE
DROP TABLE IF EXISTS `intuitive_care`.`csv_import_geral`;
CREATE TABLE  `intuitive_care`.`csv_import_geral` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DIA` date DEFAULT NULL,
  `REG_ANS` varchar(45) NOT NULL DEFAULT '',
  `CD_CONTA_CONTABIL` varchar(45) NOT NULL DEFAULT '',
  `DESCRICAO` varchar(100) NOT NULL DEFAULT '',
  `VL_SALDO_FINAL` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1179631 DEFAULT CHARSET=latin1;

-- QUERY LOAD
LOAD DATA LOCAL INFILE 'C:/Users/naoti/Documents/Projetos/estagio_IntuitiveCare/q3/csv/3T2020.csv'
INTO TABLE csv_import_geral
FIELDS TERMINATED BY ';' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DIA = STR_TO_DATE(@DIA, '%m/%d/%Y');


-- QUERY PROCURA TRIMESTRE
SELECT 
    ID, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, SUM(VL_SALDO_FINAL) AS SALDO 
FROM csv_import_geral
WHERE
  (dia BETWEEN '2020-01-01' AND '2020-31-03') and
  DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR'
GROUP BY REG_ANS ORDER BY SALDO DESC LIMIT 10

-- QUERY PROCURA ANO
SELECT 
    ID, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, SUM(VL_SALDO_FINAL) AS SALDO 
FROM csv_import_geral
WHERE
  (dia BETWEEN '2020-01-01' AND '2020-31-12') and
  DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR'
GROUP BY REG_ANS ORDER BY SALDO DESC LIMIT 10